name: RSpec

on: [push]

jobs:
  RSpec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', '3.2', 'head']
    env:
      NO_STEEP: "Because we need to test on versions that are older than steep supports"

    steps:
      - uses: actions/checkout@v4

      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run RSpec
        run: bundle exec rspec
