name: StandardRB

on: [push]

jobs:
  StandardRB:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: StandardRB Linter
        uses: andrewmcodes/standardrb-action@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
